// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"interface_project/ent/fileentity"
	"interface_project/ent/user"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// FileEntity is the model entity for the FileEntity schema.
type FileEntity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Size holds the value of the "size" field.
	Size int16 `json:"size,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted bool `json:"deleted,omitempty"`
	// CreatedDate holds the value of the "created_date" field.
	CreatedDate time.Time `json:"created_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileEntityQuery when eager-loading is set.
	Edges      FileEntityEdges `json:"edges"`
	user_files *int
}

// FileEntityEdges holds the relations/edges for other nodes in the graph.
type FileEntityEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Wordnodes holds the value of the wordnodes edge.
	Wordnodes []*WordNode `json:"wordnodes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileEntityEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// WordnodesOrErr returns the Wordnodes value or an error if the edge
// was not loaded in eager-loading.
func (e FileEntityEdges) WordnodesOrErr() ([]*WordNode, error) {
	if e.loadedTypes[1] {
		return e.Wordnodes, nil
	}
	return nil, &NotLoadedError{edge: "wordnodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileEntity) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case fileentity.FieldDeleted:
			values[i] = new(sql.NullBool)
		case fileentity.FieldID, fileentity.FieldSize:
			values[i] = new(sql.NullInt64)
		case fileentity.FieldPath, fileentity.FieldName:
			values[i] = new(sql.NullString)
		case fileentity.FieldCreatedDate:
			values[i] = new(sql.NullTime)
		case fileentity.ForeignKeys[0]: // user_files
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type FileEntity", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileEntity fields.
func (fe *FileEntity) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fileentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fe.ID = int(value.Int64)
		case fileentity.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				fe.Path = value.String
			}
		case fileentity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				fe.Name = value.String
			}
		case fileentity.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				fe.Size = int16(value.Int64)
			}
		case fileentity.FieldDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deleted", values[i])
			} else if value.Valid {
				fe.Deleted = value.Bool
			}
		case fileentity.FieldCreatedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_date", values[i])
			} else if value.Valid {
				fe.CreatedDate = value.Time
			}
		case fileentity.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_files", value)
			} else if value.Valid {
				fe.user_files = new(int)
				*fe.user_files = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryOwner queries the "owner" edge of the FileEntity entity.
func (fe *FileEntity) QueryOwner() *UserQuery {
	return (&FileEntityClient{config: fe.config}).QueryOwner(fe)
}

// QueryWordnodes queries the "wordnodes" edge of the FileEntity entity.
func (fe *FileEntity) QueryWordnodes() *WordNodeQuery {
	return (&FileEntityClient{config: fe.config}).QueryWordnodes(fe)
}

// Update returns a builder for updating this FileEntity.
// Note that you need to call FileEntity.Unwrap() before calling this method if this FileEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (fe *FileEntity) Update() *FileEntityUpdateOne {
	return (&FileEntityClient{config: fe.config}).UpdateOne(fe)
}

// Unwrap unwraps the FileEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fe *FileEntity) Unwrap() *FileEntity {
	tx, ok := fe.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileEntity is not a transactional entity")
	}
	fe.config.driver = tx.drv
	return fe
}

// String implements the fmt.Stringer.
func (fe *FileEntity) String() string {
	var builder strings.Builder
	builder.WriteString("FileEntity(")
	builder.WriteString(fmt.Sprintf("id=%v", fe.ID))
	builder.WriteString(", path=")
	builder.WriteString(fe.Path)
	builder.WriteString(", name=")
	builder.WriteString(fe.Name)
	builder.WriteString(", size=")
	builder.WriteString(fmt.Sprintf("%v", fe.Size))
	builder.WriteString(", deleted=")
	builder.WriteString(fmt.Sprintf("%v", fe.Deleted))
	builder.WriteString(", created_date=")
	builder.WriteString(fe.CreatedDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FileEntities is a parsable slice of FileEntity.
type FileEntities []*FileEntity

func (fe FileEntities) config(cfg config) {
	for _i := range fe {
		fe[_i].config = cfg
	}
}
