// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"interface_project/ent/predicate"
	"interface_project/ent/searchkeyword"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SearchKeywordQuery is the builder for querying SearchKeyword entities.
type SearchKeywordQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SearchKeyword
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SearchKeywordQuery builder.
func (skq *SearchKeywordQuery) Where(ps ...predicate.SearchKeyword) *SearchKeywordQuery {
	skq.predicates = append(skq.predicates, ps...)
	return skq
}

// Limit adds a limit step to the query.
func (skq *SearchKeywordQuery) Limit(limit int) *SearchKeywordQuery {
	skq.limit = &limit
	return skq
}

// Offset adds an offset step to the query.
func (skq *SearchKeywordQuery) Offset(offset int) *SearchKeywordQuery {
	skq.offset = &offset
	return skq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (skq *SearchKeywordQuery) Unique(unique bool) *SearchKeywordQuery {
	skq.unique = &unique
	return skq
}

// Order adds an order step to the query.
func (skq *SearchKeywordQuery) Order(o ...OrderFunc) *SearchKeywordQuery {
	skq.order = append(skq.order, o...)
	return skq
}

// First returns the first SearchKeyword entity from the query.
// Returns a *NotFoundError when no SearchKeyword was found.
func (skq *SearchKeywordQuery) First(ctx context.Context) (*SearchKeyword, error) {
	nodes, err := skq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{searchkeyword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (skq *SearchKeywordQuery) FirstX(ctx context.Context) *SearchKeyword {
	node, err := skq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SearchKeyword ID from the query.
// Returns a *NotFoundError when no SearchKeyword ID was found.
func (skq *SearchKeywordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = skq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{searchkeyword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (skq *SearchKeywordQuery) FirstIDX(ctx context.Context) int {
	id, err := skq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SearchKeyword entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SearchKeyword entity is found.
// Returns a *NotFoundError when no SearchKeyword entities are found.
func (skq *SearchKeywordQuery) Only(ctx context.Context) (*SearchKeyword, error) {
	nodes, err := skq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{searchkeyword.Label}
	default:
		return nil, &NotSingularError{searchkeyword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (skq *SearchKeywordQuery) OnlyX(ctx context.Context) *SearchKeyword {
	node, err := skq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SearchKeyword ID in the query.
// Returns a *NotSingularError when more than one SearchKeyword ID is found.
// Returns a *NotFoundError when no entities are found.
func (skq *SearchKeywordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = skq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = &NotSingularError{searchkeyword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (skq *SearchKeywordQuery) OnlyIDX(ctx context.Context) int {
	id, err := skq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SearchKeywords.
func (skq *SearchKeywordQuery) All(ctx context.Context) ([]*SearchKeyword, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return skq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (skq *SearchKeywordQuery) AllX(ctx context.Context) []*SearchKeyword {
	nodes, err := skq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SearchKeyword IDs.
func (skq *SearchKeywordQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := skq.Select(searchkeyword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (skq *SearchKeywordQuery) IDsX(ctx context.Context) []int {
	ids, err := skq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (skq *SearchKeywordQuery) Count(ctx context.Context) (int, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return skq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (skq *SearchKeywordQuery) CountX(ctx context.Context) int {
	count, err := skq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (skq *SearchKeywordQuery) Exist(ctx context.Context) (bool, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return skq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (skq *SearchKeywordQuery) ExistX(ctx context.Context) bool {
	exist, err := skq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SearchKeywordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (skq *SearchKeywordQuery) Clone() *SearchKeywordQuery {
	if skq == nil {
		return nil
	}
	return &SearchKeywordQuery{
		config:     skq.config,
		limit:      skq.limit,
		offset:     skq.offset,
		order:      append([]OrderFunc{}, skq.order...),
		predicates: append([]predicate.SearchKeyword{}, skq.predicates...),
		// clone intermediate query.
		sql:    skq.sql.Clone(),
		path:   skq.path,
		unique: skq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SearchKeyword.Query().
//		GroupBy(searchkeyword.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (skq *SearchKeywordQuery) GroupBy(field string, fields ...string) *SearchKeywordGroupBy {
	group := &SearchKeywordGroupBy{config: skq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := skq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return skq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.SearchKeyword.Query().
//		Select(searchkeyword.FieldTitle).
//		Scan(ctx, &v)
//
func (skq *SearchKeywordQuery) Select(fields ...string) *SearchKeywordSelect {
	skq.fields = append(skq.fields, fields...)
	return &SearchKeywordSelect{SearchKeywordQuery: skq}
}

func (skq *SearchKeywordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range skq.fields {
		if !searchkeyword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if skq.path != nil {
		prev, err := skq.path(ctx)
		if err != nil {
			return err
		}
		skq.sql = prev
	}
	return nil
}

func (skq *SearchKeywordQuery) sqlAll(ctx context.Context) ([]*SearchKeyword, error) {
	var (
		nodes = []*SearchKeyword{}
		_spec = skq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SearchKeyword{config: skq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, skq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (skq *SearchKeywordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := skq.querySpec()
	_spec.Node.Columns = skq.fields
	if len(skq.fields) > 0 {
		_spec.Unique = skq.unique != nil && *skq.unique
	}
	return sqlgraph.CountNodes(ctx, skq.driver, _spec)
}

func (skq *SearchKeywordQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := skq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (skq *SearchKeywordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   searchkeyword.Table,
			Columns: searchkeyword.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: searchkeyword.FieldID,
			},
		},
		From:   skq.sql,
		Unique: true,
	}
	if unique := skq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := skq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, searchkeyword.FieldID)
		for i := range fields {
			if fields[i] != searchkeyword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := skq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := skq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := skq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := skq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (skq *SearchKeywordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(skq.driver.Dialect())
	t1 := builder.Table(searchkeyword.Table)
	columns := skq.fields
	if len(columns) == 0 {
		columns = searchkeyword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if skq.sql != nil {
		selector = skq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if skq.unique != nil && *skq.unique {
		selector.Distinct()
	}
	for _, p := range skq.predicates {
		p(selector)
	}
	for _, p := range skq.order {
		p(selector)
	}
	if offset := skq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := skq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SearchKeywordGroupBy is the group-by builder for SearchKeyword entities.
type SearchKeywordGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (skgb *SearchKeywordGroupBy) Aggregate(fns ...AggregateFunc) *SearchKeywordGroupBy {
	skgb.fns = append(skgb.fns, fns...)
	return skgb
}

// Scan applies the group-by query and scans the result into the given value.
func (skgb *SearchKeywordGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := skgb.path(ctx)
	if err != nil {
		return err
	}
	skgb.sql = query
	return skgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := skgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(skgb.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := skgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) StringsX(ctx context.Context) []string {
	v, err := skgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = skgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) StringX(ctx context.Context) string {
	v, err := skgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(skgb.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := skgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) IntsX(ctx context.Context) []int {
	v, err := skgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = skgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) IntX(ctx context.Context) int {
	v, err := skgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(skgb.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := skgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := skgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = skgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) Float64X(ctx context.Context) float64 {
	v, err := skgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(skgb.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := skgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := skgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (skgb *SearchKeywordGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = skgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (skgb *SearchKeywordGroupBy) BoolX(ctx context.Context) bool {
	v, err := skgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (skgb *SearchKeywordGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range skgb.fields {
		if !searchkeyword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := skgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := skgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (skgb *SearchKeywordGroupBy) sqlQuery() *sql.Selector {
	selector := skgb.sql.Select()
	aggregation := make([]string, 0, len(skgb.fns))
	for _, fn := range skgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(skgb.fields)+len(skgb.fns))
		for _, f := range skgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(skgb.fields...)...)
}

// SearchKeywordSelect is the builder for selecting fields of SearchKeyword entities.
type SearchKeywordSelect struct {
	*SearchKeywordQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sks *SearchKeywordSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sks.prepareQuery(ctx); err != nil {
		return err
	}
	sks.sql = sks.SearchKeywordQuery.sqlQuery(ctx)
	return sks.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sks *SearchKeywordSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sks.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sks.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sks *SearchKeywordSelect) StringsX(ctx context.Context) []string {
	v, err := sks.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sks.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sks *SearchKeywordSelect) StringX(ctx context.Context) string {
	v, err := sks.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sks.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sks *SearchKeywordSelect) IntsX(ctx context.Context) []int {
	v, err := sks.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sks.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sks *SearchKeywordSelect) IntX(ctx context.Context) int {
	v, err := sks.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sks.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sks *SearchKeywordSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sks.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sks.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sks *SearchKeywordSelect) Float64X(ctx context.Context) float64 {
	v, err := sks.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sks.fields) > 1 {
		return nil, errors.New("ent: SearchKeywordSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sks *SearchKeywordSelect) BoolsX(ctx context.Context) []bool {
	v, err := sks.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sks *SearchKeywordSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sks.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{searchkeyword.Label}
	default:
		err = fmt.Errorf("ent: SearchKeywordSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sks *SearchKeywordSelect) BoolX(ctx context.Context) bool {
	v, err := sks.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sks *SearchKeywordSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sks.sql.Query()
	if err := sks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
