// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"interface_project/ent/predicate"
	"interface_project/ent/searchkeyword"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SearchKeywordDelete is the builder for deleting a SearchKeyword entity.
type SearchKeywordDelete struct {
	config
	hooks    []Hook
	mutation *SearchKeywordMutation
}

// Where appends a list predicates to the SearchKeywordDelete builder.
func (skd *SearchKeywordDelete) Where(ps ...predicate.SearchKeyword) *SearchKeywordDelete {
	skd.mutation.Where(ps...)
	return skd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (skd *SearchKeywordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(skd.hooks) == 0 {
		affected, err = skd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SearchKeywordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			skd.mutation = mutation
			affected, err = skd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(skd.hooks) - 1; i >= 0; i-- {
			if skd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = skd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, skd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (skd *SearchKeywordDelete) ExecX(ctx context.Context) int {
	n, err := skd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (skd *SearchKeywordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: searchkeyword.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: searchkeyword.FieldID,
			},
		},
	}
	if ps := skd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, skd.driver, _spec)
}

// SearchKeywordDeleteOne is the builder for deleting a single SearchKeyword entity.
type SearchKeywordDeleteOne struct {
	skd *SearchKeywordDelete
}

// Exec executes the deletion query.
func (skdo *SearchKeywordDeleteOne) Exec(ctx context.Context) error {
	n, err := skdo.skd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{searchkeyword.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (skdo *SearchKeywordDeleteOne) ExecX(ctx context.Context) {
	skdo.skd.ExecX(ctx)
}
