// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"interface_project/ent/predicate"
	"interface_project/ent/word"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordUpdate is the builder for updating Word entities.
type WordUpdate struct {
	config
	hooks    []Hook
	mutation *WordMutation
}

// Where appends a list predicates to the WordUpdate builder.
func (wu *WordUpdate) Where(ps ...predicate.Word) *WordUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetTitle sets the "title" field.
func (wu *WordUpdate) SetTitle(s string) *WordUpdate {
	wu.mutation.SetTitle(s)
	return wu
}

// SetMeaning sets the "meaning" field.
func (wu *WordUpdate) SetMeaning(s string) *WordUpdate {
	wu.mutation.SetMeaning(s)
	return wu
}

// SetNillableMeaning sets the "meaning" field if the given value is not nil.
func (wu *WordUpdate) SetNillableMeaning(s *string) *WordUpdate {
	if s != nil {
		wu.SetMeaning(*s)
	}
	return wu
}

// ClearMeaning clears the value of the "meaning" field.
func (wu *WordUpdate) ClearMeaning() *WordUpdate {
	wu.mutation.ClearMeaning()
	return wu
}

// SetSentence sets the "sentence" field.
func (wu *WordUpdate) SetSentence(s string) *WordUpdate {
	wu.mutation.SetSentence(s)
	return wu
}

// SetNillableSentence sets the "sentence" field if the given value is not nil.
func (wu *WordUpdate) SetNillableSentence(s *string) *WordUpdate {
	if s != nil {
		wu.SetSentence(*s)
	}
	return wu
}

// ClearSentence clears the value of the "sentence" field.
func (wu *WordUpdate) ClearSentence() *WordUpdate {
	wu.mutation.ClearSentence()
	return wu
}

// SetDuration sets the "duration" field.
func (wu *WordUpdate) SetDuration(s string) *WordUpdate {
	wu.mutation.SetDuration(s)
	return wu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (wu *WordUpdate) SetNillableDuration(s *string) *WordUpdate {
	if s != nil {
		wu.SetDuration(*s)
	}
	return wu
}

// ClearDuration clears the value of the "duration" field.
func (wu *WordUpdate) ClearDuration() *WordUpdate {
	wu.mutation.ClearDuration()
	return wu
}

// Mutation returns the WordMutation object of the builder.
func (wu *WordUpdate) Mutation() *WordMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WordUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wu.hooks) == 0 {
		if err = wu.check(); err != nil {
			return 0, err
		}
		affected, err = wu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wu.check(); err != nil {
				return 0, err
			}
			wu.mutation = mutation
			affected, err = wu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wu.hooks) - 1; i >= 0; i-- {
			if wu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WordUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WordUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WordUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WordUpdate) check() error {
	if v, ok := wu.mutation.Title(); ok {
		if err := word.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Word.title": %w`, err)}
		}
	}
	return nil
}

func (wu *WordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   word.Table,
			Columns: word.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: word.FieldID,
			},
		},
	}
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldTitle,
		})
	}
	if value, ok := wu.mutation.Meaning(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldMeaning,
		})
	}
	if wu.mutation.MeaningCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldMeaning,
		})
	}
	if value, ok := wu.mutation.Sentence(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldSentence,
		})
	}
	if wu.mutation.SentenceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldSentence,
		})
	}
	if value, ok := wu.mutation.Duration(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldDuration,
		})
	}
	if wu.mutation.DurationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldDuration,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{word.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// WordUpdateOne is the builder for updating a single Word entity.
type WordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WordMutation
}

// SetTitle sets the "title" field.
func (wuo *WordUpdateOne) SetTitle(s string) *WordUpdateOne {
	wuo.mutation.SetTitle(s)
	return wuo
}

// SetMeaning sets the "meaning" field.
func (wuo *WordUpdateOne) SetMeaning(s string) *WordUpdateOne {
	wuo.mutation.SetMeaning(s)
	return wuo
}

// SetNillableMeaning sets the "meaning" field if the given value is not nil.
func (wuo *WordUpdateOne) SetNillableMeaning(s *string) *WordUpdateOne {
	if s != nil {
		wuo.SetMeaning(*s)
	}
	return wuo
}

// ClearMeaning clears the value of the "meaning" field.
func (wuo *WordUpdateOne) ClearMeaning() *WordUpdateOne {
	wuo.mutation.ClearMeaning()
	return wuo
}

// SetSentence sets the "sentence" field.
func (wuo *WordUpdateOne) SetSentence(s string) *WordUpdateOne {
	wuo.mutation.SetSentence(s)
	return wuo
}

// SetNillableSentence sets the "sentence" field if the given value is not nil.
func (wuo *WordUpdateOne) SetNillableSentence(s *string) *WordUpdateOne {
	if s != nil {
		wuo.SetSentence(*s)
	}
	return wuo
}

// ClearSentence clears the value of the "sentence" field.
func (wuo *WordUpdateOne) ClearSentence() *WordUpdateOne {
	wuo.mutation.ClearSentence()
	return wuo
}

// SetDuration sets the "duration" field.
func (wuo *WordUpdateOne) SetDuration(s string) *WordUpdateOne {
	wuo.mutation.SetDuration(s)
	return wuo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (wuo *WordUpdateOne) SetNillableDuration(s *string) *WordUpdateOne {
	if s != nil {
		wuo.SetDuration(*s)
	}
	return wuo
}

// ClearDuration clears the value of the "duration" field.
func (wuo *WordUpdateOne) ClearDuration() *WordUpdateOne {
	wuo.mutation.ClearDuration()
	return wuo
}

// Mutation returns the WordMutation object of the builder.
func (wuo *WordUpdateOne) Mutation() *WordMutation {
	return wuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WordUpdateOne) Select(field string, fields ...string) *WordUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Word entity.
func (wuo *WordUpdateOne) Save(ctx context.Context) (*Word, error) {
	var (
		err  error
		node *Word
	)
	if len(wuo.hooks) == 0 {
		if err = wuo.check(); err != nil {
			return nil, err
		}
		node, err = wuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wuo.check(); err != nil {
				return nil, err
			}
			wuo.mutation = mutation
			node, err = wuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wuo.hooks) - 1; i >= 0; i-- {
			if wuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WordUpdateOne) SaveX(ctx context.Context) *Word {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WordUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WordUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WordUpdateOne) check() error {
	if v, ok := wuo.mutation.Title(); ok {
		if err := word.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Word.title": %w`, err)}
		}
	}
	return nil
}

func (wuo *WordUpdateOne) sqlSave(ctx context.Context) (_node *Word, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   word.Table,
			Columns: word.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: word.FieldID,
			},
		},
	}
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Word.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, word.FieldID)
		for _, f := range fields {
			if !word.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != word.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldTitle,
		})
	}
	if value, ok := wuo.mutation.Meaning(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldMeaning,
		})
	}
	if wuo.mutation.MeaningCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldMeaning,
		})
	}
	if value, ok := wuo.mutation.Sentence(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldSentence,
		})
	}
	if wuo.mutation.SentenceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldSentence,
		})
	}
	if value, ok := wuo.mutation.Duration(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: word.FieldDuration,
		})
	}
	if wuo.mutation.DurationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: word.FieldDuration,
		})
	}
	_node = &Word{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{word.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
