// Code generated by entc, DO NOT EDIT.

package sentence

import (
	"interface_project/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Sentence applies equality check predicate on the "sentence" field. It's identical to SentenceEQ.
func Sentence(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSentence), v))
	})
}

// SentenceEQ applies the EQ predicate on the "sentence" field.
func SentenceEQ(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSentence), v))
	})
}

// SentenceNEQ applies the NEQ predicate on the "sentence" field.
func SentenceNEQ(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSentence), v))
	})
}

// SentenceIn applies the In predicate on the "sentence" field.
func SentenceIn(vs ...string) predicate.Sentence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sentence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSentence), v...))
	})
}

// SentenceNotIn applies the NotIn predicate on the "sentence" field.
func SentenceNotIn(vs ...string) predicate.Sentence {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sentence(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSentence), v...))
	})
}

// SentenceGT applies the GT predicate on the "sentence" field.
func SentenceGT(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSentence), v))
	})
}

// SentenceGTE applies the GTE predicate on the "sentence" field.
func SentenceGTE(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSentence), v))
	})
}

// SentenceLT applies the LT predicate on the "sentence" field.
func SentenceLT(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSentence), v))
	})
}

// SentenceLTE applies the LTE predicate on the "sentence" field.
func SentenceLTE(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSentence), v))
	})
}

// SentenceContains applies the Contains predicate on the "sentence" field.
func SentenceContains(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSentence), v))
	})
}

// SentenceHasPrefix applies the HasPrefix predicate on the "sentence" field.
func SentenceHasPrefix(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSentence), v))
	})
}

// SentenceHasSuffix applies the HasSuffix predicate on the "sentence" field.
func SentenceHasSuffix(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSentence), v))
	})
}

// SentenceEqualFold applies the EqualFold predicate on the "sentence" field.
func SentenceEqualFold(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSentence), v))
	})
}

// SentenceContainsFold applies the ContainsFold predicate on the "sentence" field.
func SentenceContainsFold(v string) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSentence), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sentence) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sentence) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sentence) predicate.Sentence {
	return predicate.Sentence(func(s *sql.Selector) {
		p(s.Not())
	})
}
