// Code generated by entc, DO NOT EDIT.

package word

import (
	"interface_project/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// Meaning applies equality check predicate on the "meaning" field. It's identical to MeaningEQ.
func Meaning(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMeaning), v))
	})
}

// Sentence applies equality check predicate on the "sentence" field. It's identical to SentenceEQ.
func Sentence(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSentence), v))
	})
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDuration), v))
	})
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTitle), v))
	})
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTitle), v))
	})
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTitle), v...))
	})
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTitle), v...))
	})
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTitle), v))
	})
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTitle), v))
	})
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTitle), v))
	})
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTitle), v))
	})
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTitle), v))
	})
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTitle), v))
	})
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTitle), v))
	})
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTitle), v))
	})
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTitle), v))
	})
}

// MeaningEQ applies the EQ predicate on the "meaning" field.
func MeaningEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMeaning), v))
	})
}

// MeaningNEQ applies the NEQ predicate on the "meaning" field.
func MeaningNEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMeaning), v))
	})
}

// MeaningIn applies the In predicate on the "meaning" field.
func MeaningIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMeaning), v...))
	})
}

// MeaningNotIn applies the NotIn predicate on the "meaning" field.
func MeaningNotIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMeaning), v...))
	})
}

// MeaningGT applies the GT predicate on the "meaning" field.
func MeaningGT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMeaning), v))
	})
}

// MeaningGTE applies the GTE predicate on the "meaning" field.
func MeaningGTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMeaning), v))
	})
}

// MeaningLT applies the LT predicate on the "meaning" field.
func MeaningLT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMeaning), v))
	})
}

// MeaningLTE applies the LTE predicate on the "meaning" field.
func MeaningLTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMeaning), v))
	})
}

// MeaningContains applies the Contains predicate on the "meaning" field.
func MeaningContains(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMeaning), v))
	})
}

// MeaningHasPrefix applies the HasPrefix predicate on the "meaning" field.
func MeaningHasPrefix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMeaning), v))
	})
}

// MeaningHasSuffix applies the HasSuffix predicate on the "meaning" field.
func MeaningHasSuffix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMeaning), v))
	})
}

// MeaningIsNil applies the IsNil predicate on the "meaning" field.
func MeaningIsNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldMeaning)))
	})
}

// MeaningNotNil applies the NotNil predicate on the "meaning" field.
func MeaningNotNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldMeaning)))
	})
}

// MeaningEqualFold applies the EqualFold predicate on the "meaning" field.
func MeaningEqualFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMeaning), v))
	})
}

// MeaningContainsFold applies the ContainsFold predicate on the "meaning" field.
func MeaningContainsFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMeaning), v))
	})
}

// SentenceEQ applies the EQ predicate on the "sentence" field.
func SentenceEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSentence), v))
	})
}

// SentenceNEQ applies the NEQ predicate on the "sentence" field.
func SentenceNEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSentence), v))
	})
}

// SentenceIn applies the In predicate on the "sentence" field.
func SentenceIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSentence), v...))
	})
}

// SentenceNotIn applies the NotIn predicate on the "sentence" field.
func SentenceNotIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSentence), v...))
	})
}

// SentenceGT applies the GT predicate on the "sentence" field.
func SentenceGT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSentence), v))
	})
}

// SentenceGTE applies the GTE predicate on the "sentence" field.
func SentenceGTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSentence), v))
	})
}

// SentenceLT applies the LT predicate on the "sentence" field.
func SentenceLT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSentence), v))
	})
}

// SentenceLTE applies the LTE predicate on the "sentence" field.
func SentenceLTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSentence), v))
	})
}

// SentenceContains applies the Contains predicate on the "sentence" field.
func SentenceContains(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSentence), v))
	})
}

// SentenceHasPrefix applies the HasPrefix predicate on the "sentence" field.
func SentenceHasPrefix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSentence), v))
	})
}

// SentenceHasSuffix applies the HasSuffix predicate on the "sentence" field.
func SentenceHasSuffix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSentence), v))
	})
}

// SentenceIsNil applies the IsNil predicate on the "sentence" field.
func SentenceIsNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSentence)))
	})
}

// SentenceNotNil applies the NotNil predicate on the "sentence" field.
func SentenceNotNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSentence)))
	})
}

// SentenceEqualFold applies the EqualFold predicate on the "sentence" field.
func SentenceEqualFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSentence), v))
	})
}

// SentenceContainsFold applies the ContainsFold predicate on the "sentence" field.
func SentenceContainsFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSentence), v))
	})
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDuration), v))
	})
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDuration), v))
	})
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDuration), v...))
	})
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...string) predicate.Word {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Word(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDuration), v...))
	})
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDuration), v))
	})
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDuration), v))
	})
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDuration), v))
	})
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDuration), v))
	})
}

// DurationContains applies the Contains predicate on the "duration" field.
func DurationContains(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDuration), v))
	})
}

// DurationHasPrefix applies the HasPrefix predicate on the "duration" field.
func DurationHasPrefix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDuration), v))
	})
}

// DurationHasSuffix applies the HasSuffix predicate on the "duration" field.
func DurationHasSuffix(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDuration), v))
	})
}

// DurationIsNil applies the IsNil predicate on the "duration" field.
func DurationIsNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDuration)))
	})
}

// DurationNotNil applies the NotNil predicate on the "duration" field.
func DurationNotNil() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDuration)))
	})
}

// DurationEqualFold applies the EqualFold predicate on the "duration" field.
func DurationEqualFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDuration), v))
	})
}

// DurationContainsFold applies the ContainsFold predicate on the "duration" field.
func DurationContainsFold(v string) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDuration), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Word) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Word) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Word) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		p(s.Not())
	})
}
