// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// FileEntity is the predicate function for fileentity builders.
type FileEntity func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// SearchKeyword is the predicate function for searchkeyword builders.
type SearchKeyword func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Word is the predicate function for word builders.
type Word func(*sql.Selector)
